"""initial

Revision ID: 31c31a8e0f63
Revises: 
Create Date: 2026-07-05 11:34:58.889543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c31a8e0f63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_tg_chat_id'), 'chats', ['tg_chat_id'], unique=True)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_domain', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_domain', 'port', name='uix_server_ip_port')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('lang', sa.String(length=2), server_default='ru', nullable=False),
    sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('premium_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('monitored_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('show_tps', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('show_motd', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_players', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('gamechat_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('interval_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitored_servers')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('servers')
    op.drop_index(op.f('ix_chats_tg_chat_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
